name: Auto Update .app-files

on:
  push:
    branches:
      - main
    paths:
      - 'ct/**.sh'
  workflow_dispatch:

jobs:
  update-app-files:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Disable file mode changes detection
      - name: Disable file mode changes
        run: git config core.fileMode false

      # Step 3: Set up Git user for committing changes
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 4: Install figlet
      - name: Install figlet
        run: sudo apt-get install -y figlet

      # Step 5: Run the updated generate-app-files.sh script
      - name: Run generate-app-files.sh
        run: |
          chmod +x .github/workflows/scripts/generate-app-headers.sh
          .github/workflows/scripts/generate-app-headers.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Commit and push changes directly
      - name: Commit and push changes
        run: |
          git add -A
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update .app files"
            git push origin main
          else
            echo "No changes to commit."
          fi
