name: Generate Combined App List

on:
  schedule:
    - cron: '0 0 * * *' # Einmal täglich um Mitternacht
  push:
    branches:
      - main
  pull_request:

jobs:
  generate_combined_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Figlet
        run: sudo apt-get install -y figlet

      - name: Run generate_combined_file script
        run: |
          bash .github/workflows/generate_combined_file.sh

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./misc/combined.txt
          git commit -m "Update combined.txt"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
